language: node_js
node_js:
- '0.10'
before_install: npm install -g grunt-cli
script: grunt deploy
deploy:
  provider: s3
  access_key_id: "AKIAJ5RMM3264VMARJQQ"
  secret_access_key:
    secure: "N0vTpvBUaqsoTKgA/Jq7GSl1oeg5ntEmhMrfjr4NqM9HQpTIRR7h1KTBrAB74+Y2WAZwhW0p1Vulk5c80u/dw3Uecc/v6QXB6HZCfmK28x4tRB4ZXpZmiPSK3WVSaILVynoDFelVnn0X+Z17wG30uLHvqtpZq9T4M9Y1YH6YnnE="
  bucket: docs.particle.io
  skip_cleanup: true
  local-dir: build
  on:
    repo: spark/docs
    branch: master
