language: node_js
node_js:
- '0.10'
before_install: npm install -g grunt-cli
script: grunt deploy
deploy:
  provider: s3
  access_key_id: "AKIAJ5RMM3264VMARJQQ"
  secret_access_key:
    secure: "PxLwFsa59snXptiuugDTXepCDuuXF1uqUJkI3FvhUl7y8RAgMOU3JeMyDUbN633DDrb4PPGeRt9Yf+tfxsZehluEFeqP+O6GDBsQgZU8jUY4kRQ4XLv3Mea3BcJyATmvyFhWL25CsiY1vTZccrHxmxvBe96boxU4zOenYbrtbYg="
  bucket: docs.particle.io
  skip_cleanup: true
  local-dir: build
  on:
    repo: spark/docs
    branch: master
