language: node_js
node_js:
- '0.10'
before_install: npm install -g grunt-cli
script: grunt deploy
deploy:
  provider: s3
  access_key_id: AKIAJ5RMM3264VMARJQQ
  secret_access_key:
    secure: DgdwuAHQ9cZ6Rb/OncDLu/E9v+Yzv4dOgWW0Xo0QcUhWVuZECzLck9xNf0qrKwrAcy4n+I8s8zw9ake6lOriVrW4h9w8Mo8G0BVIruz08f+ZvBi6RN7nCoDATX5xKpH7UUT92qkhx1xnPgoMfhb/rZRd5AuRrJLFk8jCABAyavo=
  bucket: docs.particle.io
  skip_cleanup: true
  local-dir: build
  on:
    repo: spark/docs-private
    branch: feature/restructure-docs
